name: my first action

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello world test"
      - name: multiline script
        run: |
          note -v
          npm -v